<?php

return [
    0 => [
        'id'         => 1,
        'parent_id'  => 0,
        'order'      => 1,
        'title'      => 'Index',
        'icon'       => 'fa-bar-chart',
        'uri'        => '/',
        'permission' => null,
        'created_at' => null,
        'updated_at' => null,
    ],
    1 => [
        'id'         => 2,
        'parent_id'  => 0,
        'order'      => 2,
        'title'      => 'Admin',
        'icon'       => 'fa-tasks',
        'uri'        => '',
        'permission' => null,
        'created_at' => null,
        'updated_at' => null,
    ],
    2 => [
        'id'         => 3,
        'parent_id'  => 2,
        'order'      => 3,
        'title'      => 'Users',
        'icon'       => 'fa-users',
        'uri'        => 'auth/users',
        'permission' => null,
        'created_at' => null,
        'updated_at' => null,
    ],
    3 => [
        'id'         => 4,
        'parent_id'  => 2,
        'order'      => 4,
        'title'      => 'Roles',
        'icon'       => 'fa-user',
        'uri'        => 'auth/roles',
        'permission' => null,
        'created_at' => null,
        'updated_at' => null,
    ],
    4 => [
        'id'         => 5,
        'parent_id'  => 2,
        'order'      => 5,
        'title'      => 'Permission',
        'icon'       => 'fa-ban',
        'uri'        => 'auth/permissions',
        'permission' => null,
        'created_at' => null,
        'updated_at' => null,
    ],
    5 => [
        'id'         => 6,
        'parent_id'  => 2,
        'order'      => 6,
        'title'      => 'Menu',
        'icon'       => 'fa-bars',
        'uri'        => 'auth/menu',
        'permission' => null,
        'created_at' => null,
        'updated_at' => null,
    ],
    6 => [
        'id'         => 7,
        'parent_id'  => 2,
        'order'      => 7,
        'title'      => 'Operation log',
        'icon'       => 'fa-history',
        'uri'        => 'auth/logs',
        'permission' => null,
        'created_at' => null,
        'updated_at' => null,
    ],
    7 => [
        'id'         => 8,
        'parent_id'  => 0,
        'order'      => 0,
        'title'      => '用户管理',
        'icon'       => 'fa-users',
        'uri'        => 'users',
        'permission' => null,
        'created_at' => '2018-12-11 10:44:49',
        'updated_at' => '2018-12-11 10:44:49',
    ],
];